### ISSUE TITLE
[Android] Build fail?

### ISSUE THREAD

**Issue by skleest** [negativetwelve/react-native-ux-cam#30] opened 2017-02-07 06:53 UTC
Hey @negativetwelve, thanks again for the package!

Working great on iOS; not integrating on Android but am getting a build error:

```
/Users/SLEE/Github/Aura/node_modules/react-native-ux-cam/android/src/main/java/com/rnuxcam/rnuxcam/UXCamModule.java:75: error: cannot find symbol
      Object value = properties.getObject(key);
                               ^
  symbol:   method getObject(String)
  location: variable properties of type ReadableMap
/Users/SLEE/Github/Aura/node_modules/react-native-ux-cam/android/src/main/java/com/rnuxcam/rnuxcam/UXCamModule.java:76: error: no suitable method found for put(String,Object)
      map.put(key, value);
         ^
    method Map.put(String,String) is not applicable
      (argument mismatch; Object cannot be converted to String)
    method AbstractMap.put(String,String) is not applicable
      (argument mismatch; Object cannot be converted to String)
    method HashMap.put(String,String) is not applicable
      (argument mismatch; Object cannot be converted to String)
2 errors
:react-native-ux-cam:compileReleaseJavaWithJavac FAILED
```

Am I missing something here?
"react-native-ux-cam": "^2.2.2",
"react-native": "^0.39.2",

Thanks!

**Comment by negativetwelve** [comment] 2017-02-07 07:20
Hi @skleest , thanks for pointing this out. I believe this is because of a patch I had merged in without thoroughly testing :/ Just reverted the commit, will send out another version now

**Comment by negativetwelve** [comment] 2017-02-07 07:22
Published as 2.2.3, @skleest would you mind giving this version a go and see if it works? I really need to add some automated testing to this...

**Comment by skleest** [comment] 2017-02-07 18:42
Hey @negativetwelve thanks for the fast turnaround as usual! With 2.2.3 android is building and the import statement isn't causing an error, but I can't use any properties of UXCam:

`Cannot read property 'tagUserName' of undefined`

Or whichever property I use first. Also tried adding additional statements listed on UXCam documentation (https://uxcam.com/docs?#android) but with no success. Wish I could help but no experience w/ Android native at all. Any thoughts here? Thanks again.

**Comment by negativetwelve** [comment] 2017-02-07 23:27
no problem @skleest! Unfortunately, we don't have this installed on our android app yet. The android portion was actually built by @aouaki in https://github.com/negativetwelve/react-native-ux-cam/pull/15

@aouaki could you provide some insight here as to why some methods aren't working? Do you know if anything changed on the React Native side between ~0.32 and 0.39.2?

**Comment by aouaki** [comment] 2017-02-08 10:23
The error @skleest is encountering seems to be on the Javascript side. It seems like `import UXCam from 'react-native-ux-cam';` sets UXCam to _undefined_ for @skleest. Strangely enough, this is defined in https://github.com/negativetwelve/react-native-ux-cam/blob/master/src/UXCam.js so even if the native part is _broken_, it shouldn't be _undefined_.
I'll try to check if I can reproduce later today (I haven't updated to RN 0.39 yet tbh).

Cheers

**Comment by negativetwelve** [comment] 2017-02-08 10:27
@aouaki thanks for the reply! I think you're on to something here.

@skleest can you post a full stack trace here? is the error happening when you import UXCam from 'react-native-ux-cam'? or is it happening here: https://github.com/negativetwelve/react-native-ux-cam/blob/master/src/UXCam.js#L40 at the reference to RNUXCam?

**Comment by skleest** [comment] 2017-02-08 18:58
@aouaki @negativetwelve 
Thanks for the reply! Import statement is not causing error--only getting an error when I'm actually using the class as you highlighted, whichever property I use first. 

Here is the error:
```
Cannot read property 'tagUserName' of undefined
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:114
reportFatalError @ error-guard.js:44
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:71
```

I currently have app/build.gradle as well as AndroidManifest set up as in instructions, and also onCreate method as in UXCam docs. The recordings are getting uploaded to UXCam no problem.

**Comment by negativetwelve** [comment] 2017-07-20 13:25
hey there @skleest, sorry for just now getting to this...

For me, I had to add the import:

```
import com.rnuxcam.rnuxcam.UXCamPackage;
```

to my Application.java file, then add:

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          ...
          new UXCamPackage()
      );
    }
```

to add the package to the app. Let me know if those steps work for you, I'll update the readme if they do!

**Closed** 2017-08-07 22:51 UTC
Labels: android, bug

**Comment by skleest** [comment] 2017-08-07 23:58
Hey @negativetwelve sorry for checking this late! Haven't worked on Android in quite a while, will make sure to go back to it and let you know if I see any problems with it. Thanks again!
